name: 빌드 및 배포

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 이미지 빌드 단계
        run: |
          echo '이미지 빌드 1단계'
          echo '이미지 빌드 2단계'

  deploy:
    needs: build-docker-image
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo '이미지 배포 및 실행'
