name: 빌드 및 배포

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 원격저장소에서 소스를 복사
        uses: actions/checkout@v3
      - name: 소스파일을 docker image로 build
        run: docker build -t thedeny1106/my-fastapi-whoami:latest .

      - name: docker hub에 로그인
        run: docker login -u thedeny1106 -p ${{  secrets.DOCKER_PASSWORD  }}

      - name: 생성된 이미지를 docker hub에 push
        run: docker push thedeny1106/my-fastapi-whoami:latest

  deploy:
    needs: build-docker-image
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo '이미지 배포 및 실행'
